#!/bin/bash

root=$(
	while true; do
		pwd=$(pwd)
		if [ $pwd = / ]; then
			echo "not in esp8266/arduino"
			break;
		fi
		if [ -r platform.txt -a -d tools/sdk ]; then
			echo $pwd
			break;
		fi
		cd ..
	done
)

[ -d "$root" ] || exit 1

case "$1" in
	install)   install=true;;
	uninstall) install=false;;
	*)         echo "need 'install' or 'uninstall'"
	           exit 1;;
esac

replace()
{
	dir="$1"
	old="$2"
	new="$3"
	
	if $install; then
		[ -r "$root/$dir/$old.orig" ] || mv "$root/$dir/$old" "$root/$dir/$old.orig"
		rm -f "$root/$dir/$old"
		ln -s "$new" "$root/$dir/$old"
	else
		[ -r "$root/$dir/$old.orig" ] || { echo "not installed?"; exit 1; }
		rm -f "$root/$dir/$old"
		ln -s "$old.orig" "$root/$dir/$old"
	fi
}

replace tools xtensa-lx106-elf $(pwd)/xtensa-lx106-elf
replace tools/sdk/lib libgcc.a $(pwd)/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/7.2.0/libgcc.a
replace tools/sdk/lib libhal.a $(pwd)/xtensa-lx106-elf/lib/libhal.a
replace tools/sdk/libc xtensa-lx106-elf $(pwd)/xtensa-lx106-elf/xtensa-lx106-elf
