#!/bin/bash

root=$(
	while true; do
		pwd=$(pwd)
		if [ $pwd = / ]; then
			echo "not in esp8266/arduino"
			break;
		fi
		if [ -r platform.txt -a -d tools/sdk ]; then
			echo $pwd
			break;
		fi
		cd ..
	done
)

[ -d "$root" ] || exit 1

case "$1" in
	install)   install=true;;
	uninstall) install=false;;
	*)         echo "need 'install' or 'uninstall'"
	           exit 1;;
esac

replace()
{
	if [ ! -z "$4" ]; then
		echo "too may arguments, installation problem (check $(pwd)/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/ for only one version?)"
		exit 1
	fi

	dir="$1"
	old="$2"
	new="$3"
	
	if $install; then
		[ -r "$root/$dir/$old.orig" ] || mv "$root/$dir/$old" "$root/$dir/$old.orig"
		rm -f "$root/$dir/$old"
		ln -s "$new" "$root/$dir/$old"
	else
		if [ -r "$root/$dir/$old.orig" ]; then
			rm -f "$root/$dir/$old"
			mv "$root/$dir/$old.orig" "$root/$dir/$old"
		else
			echo "$root/$dir/$old was not installed"
		fi
	fi
}

replace tools xtensa-lx106-elf $(pwd)/xtensa-lx106-elf
replace tools/sdk/lib libgcc.a $(pwd)/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/*/libgcc.a
replace tools/sdk/lib libstdc++.a $(pwd)/xtensa-lx106-elf/xtensa-lx106-elf/lib/libstdc++.a
replace tools/sdk/lib libhal.a $(pwd)/xtensa-lx106-elf/lib/libhal.a
replace tools/sdk/libc xtensa-lx106-elf $(pwd)/xtensa-lx106-elf/xtensa-lx106-elf

echo ""
echo "Current toolchain version:"
echo ""
"$root/tools/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc" -v
echo ""
