# Manually started actino to build OpenOCD for Windows and upload to an artifact

name: Build MacOS
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.1.0'
    - name: Build
      run: |
        brew update
        brew install bash libtool automake libusb hidapi
        git clone https://github.com/raspberrypi/openocd.git
        pushd openocd
        git checkout rp2040
        echo Fixing GCC 12 warning
        echo ZGlmZiAtLWdpdCBhL3NyYy9oZWxwZXIvY29uZmlndXJhdGlvbi5jIGIvc3JjL2hlbHBlci9jb25m\
        aWd1cmF0aW9uLmMKaW5kZXggMTE0YWQyYzZjLi45ZjhiNGM3ZjQgMTAwNjQ0Ci0tLSBhL3NyYy9o\
        ZWxwZXIvY29uZmlndXJhdGlvbi5jCisrKyBiL3NyYy9oZWxwZXIvY29uZmlndXJhdGlvbi5jCkBA\
        IC0xNDYsNiArMTQ2LDkgQEAgaW50IHBhcnNlX2NvbmZpZ19maWxlKHN0cnVjdCBjb21tYW5kX2Nv\
        bnRleHQgKmNtZF9jdHgpCiAKIGNoYXIgKmdldF9ob21lX2Rpcihjb25zdCBjaGFyICphcHBlbmRf\
        cGF0aCkKIHsKKyNpZmRlZiBfV0lOMzIKKwljaGFyIGhvbWVwYXRoW01BWF9QQVRIXTsKKyNlbmRp\
        ZgogCWNoYXIgKmhvbWUgPSBnZXRlbnYoIkhPTUUiKTsKIAogCWlmIChob21lID09IE5VTEwpIHsK\
        QEAgLTE1NSw3ICsxNTgsNiBAQCBjaGFyICpnZXRfaG9tZV9kaXIoY29uc3QgY2hhciAqYXBwZW5k\
        X3BhdGgpCiAKIAkJaWYgKGhvbWUgPT0gTlVMTCkgewogCi0JCQljaGFyIGhvbWVwYXRoW01BWF9Q\
        QVRIXTsKIAkJCWNoYXIgKmRyaXZlID0gZ2V0ZW52KCJIT01FRFJJVkUiKTsKIAkJCWNoYXIgKnBh\
        dGggPSBnZXRlbnYoIkhPTUVQQVRIIik7CiAJCQlpZiAoZHJpdmUgJiYgcGF0aCkgewo= > b64
        base64 -d -i b64 > bug.patch
        patch -p1 < bug.patch
        echo Removing TEX issues
        echo ZGlmZiAtLWdpdCBhL2RvYy9vcGVub2NkLnRleGkgYi9kb2Mvb3Blbm9jZC50ZXhpCmluZGV4IGE1\
        Yjk0MzYyZi4uMmQ0YmU0NmNmIDEwMDY0NAotLS0gYS9kb2Mvb3Blbm9jZC50ZXhpCisrKyBiL2Rv\
        Yy9vcGVub2NkLnRleGkKQEAgLTEwOTMxLDExICsxMDkzMSwxMSBAQCBDeWdfVGhyZWFkOjp0aHJl\
        YWRfbGlzdCwgQ3lnX1NjaGVkdWxlcl9CYXNlOjpjdXJyZW50X3RocmVhZC4KIEBpdGVtIFRocmVh\
        ZFggc3ltYm9scwogX3R4X3RocmVhZF9jdXJyZW50X3B0ciwgX3R4X3RocmVhZF9jcmVhdGVkX3B0\
        ciwgX3R4X3RocmVhZF9jcmVhdGVkX2NvdW50LgogQGl0ZW0gRnJlZVJUT1Mgc3ltYm9scwotQHJh\
        Z2dlZHJpZ2h0CisKIHB4Q3VycmVudFRDQiwgcHhSZWFkeVRhc2tzTGlzdHMsIHhEZWxheWVkVGFz\
        a0xpc3QxLCB4RGVsYXllZFRhc2tMaXN0MiwKIHB4RGVsYXllZFRhc2tMaXN0LCBweE92ZXJmbG93\
        RGVsYXllZFRhc2tMaXN0LCB4UGVuZGluZ1JlYWR5TGlzdCwKIHV4Q3VycmVudE51bWJlck9mVGFz\
        a3MsIHV4VG9wVXNlZFByaW9yaXR5LgotQGVuZCByYWdnZWRyaWdodAorCiBAaXRlbSBsaW51eCBz\
        eW1ib2xzCiBpbml0X3Rhc2suCiBAaXRlbSBDaGliaU9TIHN5bWJvbHMKQEAgLTEwOTUwLDEwICsx\
        MDk1MCwxMCBAQCBPU1J1bm5pbmcsIE9TVENCQ3VyUHRyLCBPU1Rhc2tEYmdMaXN0UHRyLCBPU1Rh\
        c2tRdHkuCiBAaXRlbSBudXR0eCBzeW1ib2xzCiBnX3JlYWR5dG9ydW4sIGdfdGFza2xpc3R0YWJs\
        ZS4KIEBpdGVtIFJJT1Qgc3ltYm9scwotQHJhZ2dlZHJpZ2h0CisKIHNjaGVkX3RocmVhZHMsIHNj\
        aGVkX251bV90aHJlYWRzLCBzY2hlZF9hY3RpdmVfcGlkLCBtYXhfdGhyZWFkcywKIF90Y2JfbmFt\
        ZV9vZmZzZXQuCi1AZW5kIHJhZ2dlZHJpZ2h0CisKIEBlbmQgdGFibGUKIAogRm9yIG1vc3QgUlRP\
        UyBzdXBwb3J0ZWQgdGhlIGFib3ZlIHN5bWJvbHMgd2lsbCBiZSBleHBvcnRlZCBieSBkZWZhdWx0\
        LiBIb3dldmVyIGZvcgo= > b64.2
        base64 -d -i b64.2 > bug2.patch
        patch -p1 < bug2.patch
        bash bootstrap
        ./configure --prefix=/tmp/openocd --enable-picoprobe --enable-cmsis-dap-v2 --enable-cmsis-dap \
                    --disable-dummy --disable-rshim --disable-ftdi  --disable-stlink --disable-ti-icdi \
                    --disable-ulink --disable-usb-blaster-2 --disable-ft232r --disable-vsllink \
                    --disable-xds110  --disable-osbdm --disable-opendous --disable-aice --disable-usbprog \
                    --disable-rlink --disable-armjtagew --disable-nulink --disable-kitprog \
                    --disable-usb-blaster --disable-presto --disable-openjtag --disable-jlink \
                    --disable-parport --disable-parport-ppdev --disable-parport-giveio --disable-jtag_vpi \
                    --disable-jtag_dpi --disable-amtjtagaccel --disable-zy1000-master --disable-zy1000 \
                    --disable-ioutil --disable-bcm2835gpio --disable-imx_gpio --disable-ep93xx \
                    --disable-at91rm9200 --disable-gw16012 --disable-oocd_trace --disable-buspirate \
                    --disable-sysfsgpio --disable-xlnx-pcie-xvc --disable-minidriver-dummy \
                    --disable-remote-bitbang
        make -j
        make install
        popd
        cp -a /usr/local/Cellar/hidapi/*/lib/*.dylib /tmp/openocd/bin/.
        cp -a /usr/local/Cellar/libusb/*/lib/*.dylib /tmp/openocd/bin/.
        cp -a /usr/local/Cellar/capstone/*/lib/*.dylib /tmp/openocd/bin/.
        tar cvf openocd.macos.tar -C /tmp openocd
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: openocd.macos.tar
        path: openocd.macos.tar
