# Manually started actino to build OpenOCD for Windows and upload to an artifact

name: Picotool Build All Windows
on: [workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        install: development make libtool pkg-config autoconf automake texinfo mingw-w64-${{matrix.env}}-libusb mingw-w64-${{matrix.env}}-hidapi git mingw-w64-${{matrix.env}}-toolchain patch cmake
    - name: Build ${{matrix.env}}
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git
        git clone https://github.com/raspberrypi/picotool.git
        pushd picotool
        mkdir build
        cd build
        PICO_SDK_PATH=../../pico-sdk cmake ..
        make
        mkdir /tmp/picotool
        cp ../LICENSE.TXT picotool.exe /tmp/picotool/.
        echo Copying needed DLLs and packaging as tarball
        cp /mingw*/bin/libhidapi*.dll /tmp/picotool/bin/.
        cp /mingw*/bin/libusb*.dll /tmp/picotool/bin/.
        popd
        strip /tmp/picotool/picotool.exe
        tar cvf picotool.${{matrix.env}}.tar -C /tmp picotool
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: picotool.${{matrix.env}}.tar
        path: picotool.${{matrix.env}}.tar
